### PR TITLE
Version check

### PR DESCRIPTION
**Pull request by alewando**
Updated version checks to use ansible's `version` test instead of string compares.

### CODE REVIEW

**Comment by uk-bolly** [comment]
hi @alewando 

Great catch on this one, this is a legacy piece of prelim work for hose on rhel7 that may have had python2 or 3 installed. With rh9, this should be python3 only i am hoping? It would be good to see what amazon Linux 2022 has for its default?

We should be able to tidy this whole piece of work up and only have the python3 settings.

Please let me know.
I can also see that DCO is not passing on this PR but does on the other one you have raised.

Many thanks once again

uk-bolly

**Comment by uk-bolly** [comment]
hi @alewando 

Great catch on this one, this is a legacy piece of prelim work for hose on rhel7 that may have had python2 or 3 installed. With rh9, this should be python3 only i am hoping? It would be good to see what amazon Linux 2022 has for its default?

We should be able to tidy this whole piece of work up and only have the python3 settings.

Please let me know.
I can also see that DCO is not passing on this PR but does on the other one you have raised.

Many thanks once again

uk-bolly

**Comment by alewando** [comment]
Both RHEL9 and AL2022 are python3 only.
DCO is corrected. Some day I'll figure out how to make that a default at the repo level.

**Comment by uk-bolly** [comment]
> Both RHEL9 and AL2022 are python3 only. DCO is corrected. Some day I'll figure out how to make that a default at the repo level.

hi @alewando 

Thank again for turning that around so quickly. i tend to use settings either at global or repo gitconfig level similar to the following for signing and sign off.
Hope this helps.

[user]
        signingkey = {redacted}
        name = {redacted}
        email = {redacted}
[commit]
        gpgsign = true
[trailer "sign"]
        key = "Signed-off-by: "
        ifmissing = add
        ifexists = doNothing
        command = echo \"$(git config user.name) <$(git config user.email)>\"


with regard to the PR i will remove it and make it python3 only compliant thank you again for confirming with AL2022. With the requirement for either < or > 8.2 no longer being required for rh9.

best regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @alewando 

I have just created a new branch and PR incorporating the discussions above and a few other changes with older OS references. It runs as expected here on RH9. I will look to merge later today into devel.

Many thanks as always

uk-bolly

**Review by georgenalen — APPROVED** [review]
Comment Edit: After initially approving I noticed gpg verification was missing.

**Review by georgenalen — CHANGES_REQUESTED** [review]
The changes look good, but I noticed the commits don't have a gpg signature. Once those two commit are gpg verified we can approve. They do have the signed-off by which is a requirement as well, so you are OK there.

**Comment by uk-bolly** [comment]
hi @alewando 


Thank you again for highlighting this issue.
We seemed to have crossed over in this PR. These should now be resolved in the lastest devel branch. They have been removed as part of rhel9 only changes and rh8 requirements and checks not required.
Any further feedback you can provide with regard to running on AL2022. Happy to ensure we can get this working in conjunction.

thanks 

uk-bolly

**Comment by uk-bolly** [comment]
hi @alewando 


Thank you again for highlighting this issue.
We seemed to have crossed over in this PR. These should now be resolved in the lastest devel branch. They have been removed as part of rhel9 only changes and rh8 requirements and checks not required.
Any further feedback you can provide with regard to running on AL2022. Happy to ensure we can get this working in conjunction.

thanks 

uk-bolly

**Pull request closed without merging**
